version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: deps-v1-{{ checksum "package.json" }}
      - run:
          name: Show yarn version
          command: yarn version
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: deps-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint code
          command: yarn lint-ci
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build package
          command: yarn pack
      - run:
          name: Inspect package contents
          command: |
            tar xvf *.tgz
      - store_artifacts:
          path: coverage
          prefix: coverage
